CREATE TABLE [dbo].[Electives](
	[electiveId] [int] IDENTITY(1,1) NOT NULL,
	[ScenarioId] [int] NULL,
	[text] [varchar](150) NULL,
 CONSTRAINT [PK_Electives] PRIMARY KEY CLUSTERED 
(
	[electiveId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]